// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Buddy.proto

package com.youngo.core.model.protobuf;

public final class IMBuddy {
  private IMBuddy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IMBuddyInviteNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Buddy.IMBuddyInviteNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0201
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0201
     * </pre>
     */
    int getId();

    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    boolean hasInvitor();
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    IMBaseDefine.UserInfo getInvitor();
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    IMBaseDefine.UserInfoOrBuilder getInvitorOrBuilder();

    /**
     * <code>optional uint32 inviteeId = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    boolean hasInviteeId();
    /**
     * <code>optional uint32 inviteeId = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    int getInviteeId();
  }
  /**
   * Protobuf type {@code IM.Buddy.IMBuddyInviteNotify}
   *
   * <pre>
   *service id   0x0002
   * </pre>
   */
  public static final class IMBuddyInviteNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Buddy.IMBuddyInviteNotify)
      IMBuddyInviteNotifyOrBuilder {
    // Use IMBuddyInviteNotify.newBuilder() to construct.
    private IMBuddyInviteNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMBuddyInviteNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMBuddyInviteNotify defaultInstance;
    public static IMBuddyInviteNotify getDefaultInstance() {
      return defaultInstance;
    }

    public IMBuddyInviteNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMBuddyInviteNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              IMBaseDefine.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = invitor_.toBuilder();
              }
              invitor_ = input.readMessage(IMBaseDefine.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(invitor_);
                invitor_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              inviteeId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddyInviteNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMBuddyInviteNotify.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMBuddyInviteNotify> PARSER =
        new com.google.protobuf.AbstractParser<IMBuddyInviteNotify>() {
      public IMBuddyInviteNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMBuddyInviteNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMBuddyInviteNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0201
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0201
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int INVITOR_FIELD_NUMBER = 2;
    private IMBaseDefine.UserInfo invitor_;
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    public boolean hasInvitor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    public IMBaseDefine.UserInfo getInvitor() {
      return invitor_;
    }
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    public IMBaseDefine.UserInfoOrBuilder getInvitorOrBuilder() {
      return invitor_;
    }

    public static final int INVITEEID_FIELD_NUMBER = 3;
    private int inviteeId_;
    /**
     * <code>optional uint32 inviteeId = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    public boolean hasInviteeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 inviteeId = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    public int getInviteeId() {
      return inviteeId_;
    }

    private void initFields() {
      id_ = 0;
      invitor_ = IMBaseDefine.UserInfo.getDefaultInstance();
      inviteeId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasInvitor()) {
        if (!getInvitor().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, invitor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, inviteeId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, invitor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, inviteeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMBuddyInviteNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddyInviteNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddyInviteNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddyInviteNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddyInviteNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddyInviteNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMBuddyInviteNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMBuddyInviteNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMBuddyInviteNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddyInviteNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMBuddyInviteNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Buddy.IMBuddyInviteNotify}
     *
     * <pre>
     *service id   0x0002
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Buddy.IMBuddyInviteNotify)
        IMBuddyInviteNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyInviteNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMBuddyInviteNotify.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMBuddy.IMBuddyInviteNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInvitorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (invitorBuilder_ == null) {
          invitor_ = IMBaseDefine.UserInfo.getDefaultInstance();
        } else {
          invitorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        inviteeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor;
      }

      public IMBuddyInviteNotify getDefaultInstanceForType() {
        return IMBuddyInviteNotify.getDefaultInstance();
      }

      public IMBuddyInviteNotify build() {
        IMBuddyInviteNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMBuddyInviteNotify buildPartial() {
        IMBuddyInviteNotify result = new IMBuddyInviteNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (invitorBuilder_ == null) {
          result.invitor_ = invitor_;
        } else {
          result.invitor_ = invitorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.inviteeId_ = inviteeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMBuddyInviteNotify) {
          return mergeFrom((IMBuddyInviteNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMBuddyInviteNotify other) {
        if (other == IMBuddyInviteNotify.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasInvitor()) {
          mergeInvitor(other.getInvitor());
        }
        if (other.hasInviteeId()) {
          setInviteeId(other.getInviteeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasInvitor()) {
          if (!getInvitor().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMBuddyInviteNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMBuddyInviteNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0201
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0201
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0201
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0201
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.UserInfo invitor_ = IMBaseDefine.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder> invitorBuilder_;
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public boolean hasInvitor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public IMBaseDefine.UserInfo getInvitor() {
        if (invitorBuilder_ == null) {
          return invitor_;
        } else {
          return invitorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder setInvitor(IMBaseDefine.UserInfo value) {
        if (invitorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          invitor_ = value;
          onChanged();
        } else {
          invitorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder setInvitor(
          IMBaseDefine.UserInfo.Builder builderForValue) {
        if (invitorBuilder_ == null) {
          invitor_ = builderForValue.build();
          onChanged();
        } else {
          invitorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder mergeInvitor(IMBaseDefine.UserInfo value) {
        if (invitorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              invitor_ != IMBaseDefine.UserInfo.getDefaultInstance()) {
            invitor_ =
              IMBaseDefine.UserInfo.newBuilder(invitor_).mergeFrom(value).buildPartial();
          } else {
            invitor_ = value;
          }
          onChanged();
        } else {
          invitorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder clearInvitor() {
        if (invitorBuilder_ == null) {
          invitor_ = IMBaseDefine.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          invitorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public IMBaseDefine.UserInfo.Builder getInvitorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getInvitorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public IMBaseDefine.UserInfoOrBuilder getInvitorOrBuilder() {
        if (invitorBuilder_ != null) {
          return invitorBuilder_.getMessageOrBuilder();
        } else {
          return invitor_;
        }
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitor = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder>
          getInvitorFieldBuilder() {
        if (invitorBuilder_ == null) {
          invitorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder>(
                  getInvitor(),
                  getParentForChildren(),
                  isClean());
          invitor_ = null;
        }
        return invitorBuilder_;
      }

      private int inviteeId_ ;
      /**
       * <code>optional uint32 inviteeId = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public boolean hasInviteeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 inviteeId = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public int getInviteeId() {
        return inviteeId_;
      }
      /**
       * <code>optional uint32 inviteeId = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder setInviteeId(int value) {
        bitField0_ |= 0x00000004;
        inviteeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 inviteeId = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder clearInviteeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inviteeId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Buddy.IMBuddyInviteNotify)
    }

    static {
      defaultInstance = new IMBuddyInviteNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Buddy.IMBuddyInviteNotify)
  }

  public interface IMBuddyAgreeNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Buddy.IMBuddyAgreeNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0202
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0202
     * </pre>
     */
    int getId();

    /**
     * <code>optional uint32 invitorId = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    boolean hasInvitorId();
    /**
     * <code>optional uint32 invitorId = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    int getInvitorId();

    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    boolean hasInvitee();
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    IMBaseDefine.UserInfo getInvitee();
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    IMBaseDefine.UserInfoOrBuilder getInviteeOrBuilder();
  }
  /**
   * Protobuf type {@code IM.Buddy.IMBuddyAgreeNotify}
   */
  public static final class IMBuddyAgreeNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Buddy.IMBuddyAgreeNotify)
      IMBuddyAgreeNotifyOrBuilder {
    // Use IMBuddyAgreeNotify.newBuilder() to construct.
    private IMBuddyAgreeNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMBuddyAgreeNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMBuddyAgreeNotify defaultInstance;
    public static IMBuddyAgreeNotify getDefaultInstance() {
      return defaultInstance;
    }

    public IMBuddyAgreeNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMBuddyAgreeNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              invitorId_ = input.readUInt32();
              break;
            }
            case 26: {
              IMBaseDefine.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = invitee_.toBuilder();
              }
              invitee_ = input.readMessage(IMBaseDefine.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(invitee_);
                invitee_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddyAgreeNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMBuddyAgreeNotify.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMBuddyAgreeNotify> PARSER =
        new com.google.protobuf.AbstractParser<IMBuddyAgreeNotify>() {
      public IMBuddyAgreeNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMBuddyAgreeNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMBuddyAgreeNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0202
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0202
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int INVITORID_FIELD_NUMBER = 2;
    private int invitorId_;
    /**
     * <code>optional uint32 invitorId = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    public boolean hasInvitorId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 invitorId = 2;</code>
     *
     * <pre>
     *邀请发起人的用户信息
     * </pre>
     */
    public int getInvitorId() {
      return invitorId_;
    }

    public static final int INVITEE_FIELD_NUMBER = 3;
    private IMBaseDefine.UserInfo invitee_;
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    public boolean hasInvitee() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    public IMBaseDefine.UserInfo getInvitee() {
      return invitee_;
    }
    /**
     * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
     *
     * <pre>
     *被邀请人的用户ID
     * </pre>
     */
    public IMBaseDefine.UserInfoOrBuilder getInviteeOrBuilder() {
      return invitee_;
    }

    private void initFields() {
      id_ = 0;
      invitorId_ = 0;
      invitee_ = IMBaseDefine.UserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasInvitee()) {
        if (!getInvitee().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, invitorId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, invitee_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, invitorId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, invitee_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMBuddyAgreeNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddyAgreeNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddyAgreeNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddyAgreeNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddyAgreeNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddyAgreeNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMBuddyAgreeNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMBuddyAgreeNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMBuddyAgreeNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddyAgreeNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMBuddyAgreeNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Buddy.IMBuddyAgreeNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Buddy.IMBuddyAgreeNotify)
        IMBuddyAgreeNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyAgreeNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMBuddyAgreeNotify.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMBuddy.IMBuddyAgreeNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInviteeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        invitorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (inviteeBuilder_ == null) {
          invitee_ = IMBaseDefine.UserInfo.getDefaultInstance();
        } else {
          inviteeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor;
      }

      public IMBuddyAgreeNotify getDefaultInstanceForType() {
        return IMBuddyAgreeNotify.getDefaultInstance();
      }

      public IMBuddyAgreeNotify build() {
        IMBuddyAgreeNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMBuddyAgreeNotify buildPartial() {
        IMBuddyAgreeNotify result = new IMBuddyAgreeNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.invitorId_ = invitorId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (inviteeBuilder_ == null) {
          result.invitee_ = invitee_;
        } else {
          result.invitee_ = inviteeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMBuddyAgreeNotify) {
          return mergeFrom((IMBuddyAgreeNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMBuddyAgreeNotify other) {
        if (other == IMBuddyAgreeNotify.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasInvitorId()) {
          setInvitorId(other.getInvitorId());
        }
        if (other.hasInvitee()) {
          mergeInvitee(other.getInvitee());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasInvitee()) {
          if (!getInvitee().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMBuddyAgreeNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMBuddyAgreeNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0202
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0202
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0202
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0202
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int invitorId_ ;
      /**
       * <code>optional uint32 invitorId = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public boolean hasInvitorId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 invitorId = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public int getInvitorId() {
        return invitorId_;
      }
      /**
       * <code>optional uint32 invitorId = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder setInvitorId(int value) {
        bitField0_ |= 0x00000002;
        invitorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 invitorId = 2;</code>
       *
       * <pre>
       *邀请发起人的用户信息
       * </pre>
       */
      public Builder clearInvitorId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        invitorId_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.UserInfo invitee_ = IMBaseDefine.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder> inviteeBuilder_;
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public boolean hasInvitee() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public IMBaseDefine.UserInfo getInvitee() {
        if (inviteeBuilder_ == null) {
          return invitee_;
        } else {
          return inviteeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder setInvitee(IMBaseDefine.UserInfo value) {
        if (inviteeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          invitee_ = value;
          onChanged();
        } else {
          inviteeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder setInvitee(
          IMBaseDefine.UserInfo.Builder builderForValue) {
        if (inviteeBuilder_ == null) {
          invitee_ = builderForValue.build();
          onChanged();
        } else {
          inviteeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder mergeInvitee(IMBaseDefine.UserInfo value) {
        if (inviteeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              invitee_ != IMBaseDefine.UserInfo.getDefaultInstance()) {
            invitee_ =
              IMBaseDefine.UserInfo.newBuilder(invitee_).mergeFrom(value).buildPartial();
          } else {
            invitee_ = value;
          }
          onChanged();
        } else {
          inviteeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public Builder clearInvitee() {
        if (inviteeBuilder_ == null) {
          invitee_ = IMBaseDefine.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          inviteeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public IMBaseDefine.UserInfo.Builder getInviteeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getInviteeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      public IMBaseDefine.UserInfoOrBuilder getInviteeOrBuilder() {
        if (inviteeBuilder_ != null) {
          return inviteeBuilder_.getMessageOrBuilder();
        } else {
          return invitee_;
        }
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo invitee = 3;</code>
       *
       * <pre>
       *被邀请人的用户ID
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder>
          getInviteeFieldBuilder() {
        if (inviteeBuilder_ == null) {
          inviteeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              IMBaseDefine.UserInfo, IMBaseDefine.UserInfo.Builder, IMBaseDefine.UserInfoOrBuilder>(
                  getInvitee(),
                  getParentForChildren(),
                  isClean());
          invitee_ = null;
        }
        return inviteeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:IM.Buddy.IMBuddyAgreeNotify)
    }

    static {
      defaultInstance = new IMBuddyAgreeNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Buddy.IMBuddyAgreeNotify)
  }

  public interface IMBuddySnubbRecommendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Buddy.IMBuddySnubbRecommend)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code IM.Buddy.IMBuddySnubbRecommend}
   */
  public static final class IMBuddySnubbRecommend extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Buddy.IMBuddySnubbRecommend)
      IMBuddySnubbRecommendOrBuilder {
    // Use IMBuddySnubbRecommend.newBuilder() to construct.
    private IMBuddySnubbRecommend(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMBuddySnubbRecommend(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMBuddySnubbRecommend defaultInstance;
    public static IMBuddySnubbRecommend getDefaultInstance() {
      return defaultInstance;
    }

    public IMBuddySnubbRecommend getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMBuddySnubbRecommend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMBuddy.internal_static_IM_Buddy_IMBuddySnubbRecommend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMBuddySnubbRecommend.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMBuddySnubbRecommend> PARSER =
        new com.google.protobuf.AbstractParser<IMBuddySnubbRecommend>() {
      public IMBuddySnubbRecommend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMBuddySnubbRecommend(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMBuddySnubbRecommend> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMBuddySnubbRecommend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddySnubbRecommend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddySnubbRecommend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMBuddySnubbRecommend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMBuddySnubbRecommend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddySnubbRecommend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMBuddySnubbRecommend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMBuddySnubbRecommend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMBuddySnubbRecommend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMBuddySnubbRecommend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMBuddySnubbRecommend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Buddy.IMBuddySnubbRecommend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Buddy.IMBuddySnubbRecommend)
        IMBuddySnubbRecommendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddySnubbRecommend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMBuddySnubbRecommend.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMBuddy.IMBuddySnubbRecommend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMBuddy.internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor;
      }

      public IMBuddySnubbRecommend getDefaultInstanceForType() {
        return IMBuddySnubbRecommend.getDefaultInstance();
      }

      public IMBuddySnubbRecommend build() {
        IMBuddySnubbRecommend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMBuddySnubbRecommend buildPartial() {
        IMBuddySnubbRecommend result = new IMBuddySnubbRecommend(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMBuddySnubbRecommend) {
          return mergeFrom((IMBuddySnubbRecommend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMBuddySnubbRecommend other) {
        if (other == IMBuddySnubbRecommend.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMBuddySnubbRecommend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMBuddySnubbRecommend) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Buddy.IMBuddySnubbRecommend)
    }

    static {
      defaultInstance = new IMBuddySnubbRecommend(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Buddy.IMBuddySnubbRecommend)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Buddy_IMBuddyInviteNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Buddy_IMBuddyAgreeNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Buddy_IMBuddySnubbRecommend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016IM.Buddy.proto\022\010IM.Buddy\032\023IM.BaseDefin" +
      "e.proto\"^\n\023IMBuddyInviteNotify\022\n\n\002id\030\001 \002" +
      "(\r\022(\n\007invitor\030\002 \001(\0132\027.IM.BaseDefine.User" +
      "Info\022\021\n\tinviteeId\030\003 \001(\r\"]\n\022IMBuddyAgreeN" +
      "otify\022\n\n\002id\030\001 \002(\r\022\021\n\tinvitorId\030\002 \001(\r\022(\n\007" +
      "invitee\030\003 \001(\0132\027.IM.BaseDefine.UserInfo\"\027" +
      "\n\025IMBuddySnubbRecommendB \n\036com.youngo.co" +
      "re.model.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          IMBaseDefine.getDescriptor(),
        }, assigner);
    internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IM_Buddy_IMBuddyInviteNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Buddy_IMBuddyInviteNotify_descriptor,
        new String[] { "Id", "Invitor", "InviteeId", });
    internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IM_Buddy_IMBuddyAgreeNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Buddy_IMBuddyAgreeNotify_descriptor,
        new String[] { "Id", "InvitorId", "Invitee", });
    internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IM_Buddy_IMBuddySnubbRecommend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Buddy_IMBuddySnubbRecommend_descriptor,
        new String[] { });
    IMBaseDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
