// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Login.proto

package com.youngo.core.model.protobuf;

public final class IMLogin {
  private IMLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IMLoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Login.IMLoginReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    boolean hasPassport();
    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    String getPassport();
    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    com.google.protobuf.ByteString
        getPassportBytes();

    /**
     * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
     */
    boolean hasClientType();
    /**
     * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
     */
    IMBaseDefine.ClientType getClientType();
  }
  /**
   * Protobuf type {@code IM.Login.IMLoginReq}
   *
   * <pre>
   *用户登录请求
   * </pre>
   */
  public static final class IMLoginReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Login.IMLoginReq)
      IMLoginReqOrBuilder {
    // Use IMLoginReq.newBuilder() to construct.
    private IMLoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMLoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMLoginReq defaultInstance;
    public static IMLoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMLoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              passport_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              IMBaseDefine.ClientType value = IMBaseDefine.ClientType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                clientType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMLogin.internal_static_IM_Login_IMLoginReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMLogin.internal_static_IM_Login_IMLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMLoginReq.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMLoginReq> PARSER =
        new com.google.protobuf.AbstractParser<IMLoginReq>() {
      public IMLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMLoginReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMLoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PASSPORT_FIELD_NUMBER = 1;
    private Object passport_;
    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    public boolean hasPassport() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    public String getPassport() {
      Object ref = passport_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passport_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passport = 1;</code>
     *
     * <pre>
     *cmd id:		0x0103
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPassportBytes() {
      Object ref = passport_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 4;
    private IMBaseDefine.ClientType clientType_;
    /**
     * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
     */
    public boolean hasClientType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
     */
    public IMBaseDefine.ClientType getClientType() {
      return clientType_;
    }

    private void initFields() {
      passport_ = "";
      clientType_ = IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPassport()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPassportBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(4, clientType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPassportBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, clientType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMLoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Login.IMLoginReq}
     *
     * <pre>
     *用户登录请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Login.IMLoginReq)
        IMLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMLogin.internal_static_IM_Login_IMLoginReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMLogin.internal_static_IM_Login_IMLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMLoginReq.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMLogin.IMLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        passport_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientType_ = IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMLogin.internal_static_IM_Login_IMLoginReq_descriptor;
      }

      public IMLoginReq getDefaultInstanceForType() {
        return IMLoginReq.getDefaultInstance();
      }

      public IMLoginReq build() {
        IMLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMLoginReq buildPartial() {
        IMLoginReq result = new IMLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.passport_ = passport_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientType_ = clientType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMLoginReq) {
          return mergeFrom((IMLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMLoginReq other) {
        if (other == IMLoginReq.getDefaultInstance()) return this;
        if (other.hasPassport()) {
          bitField0_ |= 0x00000001;
          passport_ = other.passport_;
          onChanged();
        }
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPassport()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMLoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object passport_ = "";
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public boolean hasPassport() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public String getPassport() {
        Object ref = passport_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            passport_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPassportBytes() {
        Object ref = passport_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passport_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public Builder setPassport(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        passport_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public Builder clearPassport() {
        bitField0_ = (bitField0_ & ~0x00000001);
        passport_ = getDefaultInstance().getPassport();
        onChanged();
        return this;
      }
      /**
       * <code>required string passport = 1;</code>
       *
       * <pre>
       *cmd id:		0x0103
       * </pre>
       */
      public Builder setPassportBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        passport_ = value;
        onChanged();
        return this;
      }

      private IMBaseDefine.ClientType clientType_ = IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
      /**
       * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
       */
      public boolean hasClientType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
       */
      public IMBaseDefine.ClientType getClientType() {
        return clientType_;
      }
      /**
       * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
       */
      public Builder setClientType(IMBaseDefine.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        clientType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.ClientType client_type = 4;</code>
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientType_ = IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Login.IMLoginReq)
    }

    static {
      defaultInstance = new IMLoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Login.IMLoginReq)
  }

  public interface IMLoginResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Login.IMLoginRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:		0x0104
     * </pre>
     */
    boolean hasServerTime();
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:		0x0104
     * </pre>
     */
    int getServerTime();

    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    IMBaseDefine.ResultType getResultCode();
  }
  /**
   * Protobuf type {@code IM.Login.IMLoginRes}
   *
   * <pre>
   *用户登录回复
   * </pre>
   */
  public static final class IMLoginRes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Login.IMLoginRes)
      IMLoginResOrBuilder {
    // Use IMLoginRes.newBuilder() to construct.
    private IMLoginRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMLoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMLoginRes defaultInstance;
    public static IMLoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public IMLoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              IMBaseDefine.ResultType value = IMBaseDefine.ResultType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                resultCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMLogin.internal_static_IM_Login_IMLoginRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMLogin.internal_static_IM_Login_IMLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMLoginRes.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMLoginRes> PARSER =
        new com.google.protobuf.AbstractParser<IMLoginRes>() {
      public IMLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMLoginRes(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMLoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVER_TIME_FIELD_NUMBER = 1;
    private int serverTime_;
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:		0x0104
     * </pre>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:		0x0104
     * </pre>
     */
    public int getServerTime() {
      return serverTime_;
    }

    public static final int RESULT_CODE_FIELD_NUMBER = 2;
    private IMBaseDefine.ResultType resultCode_;
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public IMBaseDefine.ResultType getResultCode() {
      return resultCode_;
    }

    private void initFields() {
      serverTime_ = 0;
      resultCode_ = IMBaseDefine.ResultType.REFUSE_REASON_NONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, resultCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resultCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMLoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Login.IMLoginRes}
     *
     * <pre>
     *用户登录回复
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Login.IMLoginRes)
        IMLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMLogin.internal_static_IM_Login_IMLoginRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMLogin.internal_static_IM_Login_IMLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMLoginRes.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMLogin.IMLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMLogin.internal_static_IM_Login_IMLoginRes_descriptor;
      }

      public IMLoginRes getDefaultInstanceForType() {
        return IMLoginRes.getDefaultInstance();
      }

      public IMLoginRes build() {
        IMLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMLoginRes buildPartial() {
        IMLoginRes result = new IMLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverTime_ = serverTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMLoginRes) {
          return mergeFrom((IMLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMLoginRes other) {
        if (other == IMLoginRes.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerTime()) {
          
          return false;
        }
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMLoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverTime_ ;
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:		0x0104
       * </pre>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:		0x0104
       * </pre>
       */
      public int getServerTime() {
        return serverTime_;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:		0x0104
       * </pre>
       */
      public Builder setServerTime(int value) {
        bitField0_ |= 0x00000001;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:		0x0104
       * </pre>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.ResultType resultCode_ = IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public IMBaseDefine.ResultType getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder setResultCode(IMBaseDefine.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Login.IMLoginRes)
    }

    static {
      defaultInstance = new IMLoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Login.IMLoginRes)
  }

  public interface IMKickUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Login.IMKickUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0107
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0107
     * </pre>
     */
    int getUserId();

    /**
     * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
     */
    boolean hasKickReason();
    /**
     * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
     */
    IMBaseDefine.KickReasonType getKickReason();
  }
  /**
   * Protobuf type {@code IM.Login.IMKickUser}
   */
  public static final class IMKickUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Login.IMKickUser)
      IMKickUserOrBuilder {
    // Use IMKickUser.newBuilder() to construct.
    private IMKickUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMKickUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMKickUser defaultInstance;
    public static IMKickUser getDefaultInstance() {
      return defaultInstance;
    }

    public IMKickUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMKickUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              IMBaseDefine.KickReasonType value = IMBaseDefine.KickReasonType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                kickReason_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMLogin.internal_static_IM_Login_IMKickUser_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMLogin.internal_static_IM_Login_IMKickUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMKickUser.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMKickUser> PARSER =
        new com.google.protobuf.AbstractParser<IMKickUser>() {
      public IMKickUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMKickUser(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMKickUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0107
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0107
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int KICK_REASON_FIELD_NUMBER = 2;
    private IMBaseDefine.KickReasonType kickReason_;
    /**
     * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
     */
    public boolean hasKickReason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
     */
    public IMBaseDefine.KickReasonType getKickReason() {
      return kickReason_;
    }

    private void initFields() {
      userId_ = 0;
      kickReason_ = IMBaseDefine.KickReasonType.KICK_REASON_DUPLICATE_USER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKickReason()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, kickReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kickReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMKickUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMKickUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMKickUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMKickUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMKickUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMKickUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMKickUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMKickUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMKickUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMKickUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMKickUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Login.IMKickUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Login.IMKickUser)
        IMKickUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMLogin.internal_static_IM_Login_IMKickUser_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMLogin.internal_static_IM_Login_IMKickUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMKickUser.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMLogin.IMKickUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        kickReason_ = IMBaseDefine.KickReasonType.KICK_REASON_DUPLICATE_USER;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMLogin.internal_static_IM_Login_IMKickUser_descriptor;
      }

      public IMKickUser getDefaultInstanceForType() {
        return IMKickUser.getDefaultInstance();
      }

      public IMKickUser build() {
        IMKickUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMKickUser buildPartial() {
        IMKickUser result = new IMKickUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.kickReason_ = kickReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMKickUser) {
          return mergeFrom((IMKickUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMKickUser other) {
        if (other == IMKickUser.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasKickReason()) {
          setKickReason(other.getKickReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasKickReason()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMKickUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMKickUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0107
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0107
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0107
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0107
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.KickReasonType kickReason_ = IMBaseDefine.KickReasonType.KICK_REASON_DUPLICATE_USER;
      /**
       * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
       */
      public boolean hasKickReason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
       */
      public IMBaseDefine.KickReasonType getKickReason() {
        return kickReason_;
      }
      /**
       * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
       */
      public Builder setKickReason(IMBaseDefine.KickReasonType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        kickReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.KickReasonType kick_reason = 2;</code>
       */
      public Builder clearKickReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kickReason_ = IMBaseDefine.KickReasonType.KICK_REASON_DUPLICATE_USER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Login.IMKickUser)
    }

    static {
      defaultInstance = new IMKickUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Login.IMKickUser)
  }

  public interface IMWarningUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Login.IMWarningUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
     */
    boolean hasWarningReason();
    /**
     * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
     */
    IMBaseDefine.WarningReasonType getWarningReason();
  }
  /**
   * Protobuf type {@code IM.Login.IMWarningUser}
   */
  public static final class IMWarningUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Login.IMWarningUser)
      IMWarningUserOrBuilder {
    // Use IMWarningUser.newBuilder() to construct.
    private IMWarningUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMWarningUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMWarningUser defaultInstance;
    public static IMWarningUser getDefaultInstance() {
      return defaultInstance;
    }

    public IMWarningUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMWarningUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              IMBaseDefine.WarningReasonType value = IMBaseDefine.WarningReasonType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                warningReason_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMLogin.internal_static_IM_Login_IMWarningUser_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMLogin.internal_static_IM_Login_IMWarningUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMWarningUser.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMWarningUser> PARSER =
        new com.google.protobuf.AbstractParser<IMWarningUser>() {
      public IMWarningUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMWarningUser(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMWarningUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required uint32 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int WARNING_REASON_FIELD_NUMBER = 2;
    private IMBaseDefine.WarningReasonType warningReason_;
    /**
     * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
     */
    public boolean hasWarningReason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
     */
    public IMBaseDefine.WarningReasonType getWarningReason() {
      return warningReason_;
    }

    private void initFields() {
      userId_ = 0;
      warningReason_ = IMBaseDefine.WarningReasonType.WARNING_REASON_PROSECUTOR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWarningReason()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, warningReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, warningReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMWarningUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMWarningUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMWarningUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMWarningUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMWarningUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMWarningUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMWarningUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMWarningUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMWarningUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMWarningUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMWarningUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Login.IMWarningUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Login.IMWarningUser)
        IMWarningUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMLogin.internal_static_IM_Login_IMWarningUser_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMLogin.internal_static_IM_Login_IMWarningUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMWarningUser.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMLogin.IMWarningUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        warningReason_ = IMBaseDefine.WarningReasonType.WARNING_REASON_PROSECUTOR;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMLogin.internal_static_IM_Login_IMWarningUser_descriptor;
      }

      public IMWarningUser getDefaultInstanceForType() {
        return IMWarningUser.getDefaultInstance();
      }

      public IMWarningUser build() {
        IMWarningUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMWarningUser buildPartial() {
        IMWarningUser result = new IMWarningUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.warningReason_ = warningReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMWarningUser) {
          return mergeFrom((IMWarningUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMWarningUser other) {
        if (other == IMWarningUser.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasWarningReason()) {
          setWarningReason(other.getWarningReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasWarningReason()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMWarningUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMWarningUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.WarningReasonType warningReason_ = IMBaseDefine.WarningReasonType.WARNING_REASON_PROSECUTOR;
      /**
       * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
       */
      public boolean hasWarningReason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
       */
      public IMBaseDefine.WarningReasonType getWarningReason() {
        return warningReason_;
      }
      /**
       * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
       */
      public Builder setWarningReason(IMBaseDefine.WarningReasonType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        warningReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.WarningReasonType warning_reason = 2;</code>
       */
      public Builder clearWarningReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        warningReason_ = IMBaseDefine.WarningReasonType.WARNING_REASON_PROSECUTOR;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Login.IMWarningUser)
    }

    static {
      defaultInstance = new IMWarningUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Login.IMWarningUser)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Login_IMLoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Login_IMLoginReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Login_IMLoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Login_IMLoginRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Login_IMKickUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Login_IMKickUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Login_IMWarningUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Login_IMWarningUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016IM.Login.proto\022\010IM.Login\032\023IM.BaseDefin" +
      "e.proto\"N\n\nIMLoginReq\022\020\n\010passport\030\001 \002(\t\022" +
      ".\n\013client_type\030\004 \001(\0162\031.IM.BaseDefine.Cli" +
      "entType\"Q\n\nIMLoginRes\022\023\n\013server_time\030\001 \002" +
      "(\r\022.\n\013result_code\030\002 \002(\0162\031.IM.BaseDefine." +
      "ResultType\"Q\n\nIMKickUser\022\017\n\007user_id\030\001 \002(" +
      "\r\0222\n\013kick_reason\030\002 \002(\0162\035.IM.BaseDefine.K" +
      "ickReasonType\"Z\n\rIMWarningUser\022\017\n\007user_i" +
      "d\030\001 \002(\r\0228\n\016warning_reason\030\002 \002(\0162 .IM.Bas" +
      "eDefine.WarningReasonTypeB \n\036com.youngo.",
      "core.model.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          IMBaseDefine.getDescriptor(),
        }, assigner);
    internal_static_IM_Login_IMLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IM_Login_IMLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Login_IMLoginReq_descriptor,
        new String[] { "Passport", "ClientType", });
    internal_static_IM_Login_IMLoginRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IM_Login_IMLoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Login_IMLoginRes_descriptor,
        new String[] { "ServerTime", "ResultCode", });
    internal_static_IM_Login_IMKickUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IM_Login_IMKickUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Login_IMKickUser_descriptor,
        new String[] { "UserId", "KickReason", });
    internal_static_IM_Login_IMWarningUser_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_IM_Login_IMWarningUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Login_IMWarningUser_descriptor,
        new String[] { "UserId", "WarningReason", });
    IMBaseDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
