// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Message.proto

package com.youngo.core.model.protobuf;

public final class IMMessage {
  private IMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IMMsgDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Message.IMMsgData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    boolean hasFromUserId();
    /**
     * <code>optional uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    int getFromUserId();

    /**
     * <code>optional uint32 to_user_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    boolean hasToUserId();
    /**
     * <code>optional uint32 to_user_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    int getToUserId();

    /**
     * <code>optional uint32 msg_id = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>optional uint32 msg_id = 3;</code>
     */
    int getMsgId();

    /**
     * <code>optional uint32 create_time = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>optional uint32 create_time = 4;</code>
     */
    int getCreateTime();

    /**
     * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
     */
    IMBaseDefine.MsgType getMsgType();

    /**
     * <code>optional bytes msg_data = 6;</code>
     */
    boolean hasMsgData();
    /**
     * <code>optional bytes msg_data = 6;</code>
     */
    com.google.protobuf.ByteString getMsgData();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Message.IMMsgData}
   *
   * <pre>
   *service id  0x0003
   * </pre>
   */
  public static final class IMMsgData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Message.IMMsgData)
      IMMsgDataOrBuilder {
    // Use IMMsgData.newBuilder() to construct.
    private IMMsgData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMsgData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMMsgData defaultInstance;
    public static IMMsgData getDefaultInstance() {
      return defaultInstance;
    }

    public IMMsgData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMMsgData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromUserId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toUserId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readUInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              IMBaseDefine.MsgType value = IMBaseDefine.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                msgType_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              msgData_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000040;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMMessage.internal_static_IM_Message_IMMsgData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMMessage.internal_static_IM_Message_IMMsgData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMMsgData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMMsgData> PARSER =
        new com.google.protobuf.AbstractParser<IMMsgData>() {
      public IMMsgData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMMsgData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMMsgData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROM_USER_ID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <code>optional uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TO_USER_ID_FIELD_NUMBER = 2;
    private int toUserId_;
    /**
     * <code>optional uint32 to_user_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 to_user_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 3;
    private int msgId_;
    /**
     * <code>optional uint32 msg_id = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 msg_id = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 4;
    private int createTime_;
    /**
     * <code>optional uint32 create_time = 4;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 create_time = 4;</code>
     */
    public int getCreateTime() {
      return createTime_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 5;
    private IMBaseDefine.MsgType msgType_;
    /**
     * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
     */
    public IMBaseDefine.MsgType getMsgType() {
      return msgType_;
    }

    public static final int MSG_DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString msgData_;
    /**
     * <code>optional bytes msg_data = 6;</code>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes msg_data = 6;</code>
     */
    public com.google.protobuf.ByteString getMsgData() {
      return msgData_;
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      fromUserId_ = 0;
      toUserId_ = 0;
      msgId_ = 0;
      createTime_ = 0;
      msgType_ = IMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
      msgData_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, msgData_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(20, attachData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, msgData_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMMsgData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMsgData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMsgData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMsgData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMsgData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMMsgData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMMsgData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMMsgData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMMsgData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMMsgData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMMsgData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Message.IMMsgData}
     *
     * <pre>
     *service id  0x0003
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Message.IMMsgData)
        IMMsgDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMMessage.internal_static_IM_Message_IMMsgData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMMessage.internal_static_IM_Message_IMMsgData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMMsgData.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMMessage.IMMsgData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgType_ = IMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMMessage.internal_static_IM_Message_IMMsgData_descriptor;
      }

      public IMMsgData getDefaultInstanceForType() {
        return IMMsgData.getDefaultInstance();
      }

      public IMMsgData build() {
        IMMsgData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMMsgData buildPartial() {
        IMMsgData result = new IMMsgData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgData_ = msgData_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMMsgData) {
          return mergeFrom((IMMsgData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMMsgData other) {
        if (other == IMMsgData.getDefaultInstance()) return this;
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgData()) {
          setMsgData(other.getMsgData());
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMMsgData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMMsgData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fromUserId_ ;
      /**
       * <code>optional uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>optional uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public Builder setFromUserId(int value) {
        bitField0_ |= 0x00000001;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <code>optional uint32 to_user_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 to_user_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <code>optional uint32 to_user_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public Builder setToUserId(int value) {
        bitField0_ |= 0x00000002;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 to_user_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>optional uint32 msg_id = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 msg_id = 3;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>optional uint32 msg_id = 3;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 msg_id = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int createTime_ ;
      /**
       * <code>optional uint32 create_time = 4;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 create_time = 4;</code>
       */
      public int getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional uint32 create_time = 4;</code>
       */
      public Builder setCreateTime(int value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 create_time = 4;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.MsgType msgType_ = IMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
      /**
       * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public IMBaseDefine.MsgType getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public Builder setMsgType(IMBaseDefine.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgType_ = IMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg_data = 6;</code>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes msg_data = 6;</code>
       */
      public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
      }
      /**
       * <code>optional bytes msg_data = 6;</code>
       */
      public Builder setMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg_data = 6;</code>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgData_ = getDefaultInstance().getMsgData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        attachData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        attachData_ = getDefaultInstance().getAttachData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Message.IMMsgData)
    }

    static {
      defaultInstance = new IMMsgData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Message.IMMsgData)
  }

  public interface IMMsgDataRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Message.IMMsgDataRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    int getUserId();

    /**
     * <code>required uint32 session_id = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    int getSessionId();

    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    int getMsgId();

    /**
     * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
     */
    boolean hasSessionType();
    /**
     * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
     */
    IMBaseDefine.SessionType getSessionType();
  }
  /**
   * Protobuf type {@code IM.Message.IMMsgDataRsp}
   */
  public static final class IMMsgDataRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IM.Message.IMMsgDataRsp)
      IMMsgDataRspOrBuilder {
    // Use IMMsgDataRsp.newBuilder() to construct.
    private IMMsgDataRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMsgDataRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IMMsgDataRsp defaultInstance;
    public static IMMsgDataRsp getDefaultInstance() {
      return defaultInstance;
    }

    public IMMsgDataRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IMMsgDataRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              IMBaseDefine.SessionType value = IMBaseDefine.SessionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                sessionType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMMessage.internal_static_IM_Message_IMMsgDataRsp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMMessage.internal_static_IM_Message_IMMsgDataRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMMsgDataRsp.class, Builder.class);
    }

    public static com.google.protobuf.Parser<IMMsgDataRsp> PARSER =
        new com.google.protobuf.AbstractParser<IMMsgDataRsp>() {
      public IMMsgDataRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMMsgDataRsp(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<IMMsgDataRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private int sessionId_;
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 3;
    private int msgId_;
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int SESSION_TYPE_FIELD_NUMBER = 4;
    private IMBaseDefine.SessionType sessionType_;
    /**
     * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
     */
    public boolean hasSessionType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
     */
    public IMBaseDefine.SessionType getSessionType() {
      return sessionType_;
    }

    private void initFields() {
      userId_ = 0;
      sessionId_ = 0;
      msgId_ = 0;
      sessionType_ = IMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, sessionType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sessionType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static IMMsgDataRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMsgDataRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMsgDataRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMsgDataRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMsgDataRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMMsgDataRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static IMMsgDataRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static IMMsgDataRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static IMMsgDataRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static IMMsgDataRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(IMMsgDataRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.Message.IMMsgDataRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Message.IMMsgDataRsp)
        IMMsgDataRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMMessage.internal_static_IM_Message_IMMsgDataRsp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMMessage.internal_static_IM_Message_IMMsgDataRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMMsgDataRsp.class, Builder.class);
      }

      // Construct using com.youngo.core.model.protobuf.IMMessage.IMMsgDataRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionType_ = IMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMMessage.internal_static_IM_Message_IMMsgDataRsp_descriptor;
      }

      public IMMsgDataRsp getDefaultInstanceForType() {
        return IMMsgDataRsp.getDefaultInstance();
      }

      public IMMsgDataRsp build() {
        IMMsgDataRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IMMsgDataRsp buildPartial() {
        IMMsgDataRsp result = new IMMsgDataRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionType_ = sessionType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMMsgDataRsp) {
          return mergeFrom((IMMsgDataRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMMsgDataRsp other) {
        if (other == IMMsgDataRsp.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasSessionType()) {
          setSessionType(other.getSessionType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasSessionType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IMMsgDataRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IMMsgDataRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private IMBaseDefine.SessionType sessionType_ = IMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
      /**
       * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
       */
      public boolean hasSessionType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
       */
      public IMBaseDefine.SessionType getSessionType() {
        return sessionType_;
      }
      /**
       * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder setSessionType(IMBaseDefine.SessionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        sessionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder clearSessionType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionType_ = IMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Message.IMMsgDataRsp)
    }

    static {
      defaultInstance = new IMMsgDataRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Message.IMMsgDataRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Message_IMMsgData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Message_IMMsgData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_Message_IMMsgDataRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IM_Message_IMMsgDataRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020IM.Message.proto\022\nIM.Message\032\023IM.BaseD" +
      "efine.proto\"\253\001\n\tIMMsgData\022\024\n\014from_user_i" +
      "d\030\001 \001(\r\022\022\n\nto_user_id\030\002 \001(\r\022\016\n\006msg_id\030\003 " +
      "\001(\r\022\023\n\013create_time\030\004 \001(\r\022(\n\010msg_type\030\005 \001" +
      "(\0162\026.IM.BaseDefine.MsgType\022\020\n\010msg_data\030\006" +
      " \001(\014\022\023\n\013attach_data\030\024 \001(\014\"u\n\014IMMsgDataRs" +
      "p\022\017\n\007user_id\030\001 \002(\r\022\022\n\nsession_id\030\002 \002(\r\022\016" +
      "\n\006msg_id\030\003 \002(\r\0220\n\014session_type\030\004 \002(\0162\032.I" +
      "M.BaseDefine.SessionTypeB \n\036com.youngo.c" +
      "ore.model.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          IMBaseDefine.getDescriptor(),
        }, assigner);
    internal_static_IM_Message_IMMsgData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IM_Message_IMMsgData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Message_IMMsgData_descriptor,
        new String[] { "FromUserId", "ToUserId", "MsgId", "CreateTime", "MsgType", "MsgData", "AttachData", });
    internal_static_IM_Message_IMMsgDataRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IM_Message_IMMsgDataRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IM_Message_IMMsgDataRsp_descriptor,
        new String[] { "UserId", "SessionId", "MsgId", "SessionType", });
    IMBaseDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
